server:
  port: 9090
spring:
  application:
    name: marvel-zuul

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api_1:
      path: /api_1/**
      serviceId: customer-ribbon
    api_2:
      path: /api_2/**
      serviceId: customer-feign